site_name: Boilermaker ServiceBus
site_description: Async Python background tasks with Azure ServiceBus
site_url: https://mulliganfunding.github.io/boilermaker-servicebus/
repo_url: https://github.com/MulliganFunding/boilermaker-servicebus
repo_name: MulliganFunding/boilermaker-servicebus
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Concepts: getting-started/basic-concepts.md
  - User Guide:
    - Task Registration: guides/task-registration.md
    - Callbacks & Chains: guides/callbacks-chains.md
    - Retry Policies: guides/retry-policies.md
    - Error Handling: guides/error-handling.md
    - Azure Setup: guides/azure-setup.md
    - Production Deployment: guides/production-deployment.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Patterns: examples/advanced-patterns.md
    - Testing: examples/testing.md
    - Real World Scenarios: examples/real-world-scenarios.md
  - API Reference:
    - Boilermaker: api-reference/app.md
    - Task: api-reference/task.md
    - Retries: api-reference/retries.md
    - Configuration: api-reference/config.md
    - Exceptions: api-reference/exceptions.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Debugging: troubleshooting/debugging.md
    - Performance: troubleshooting/performance.md
  - Contributing:
    - Development Setup: contributing/development.md
    - Running Tests: contributing/testing.md
    - Release Process: contributing/releasing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MulliganFunding/boilermaker-servicebus
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/boilermaker-servicebus/

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/mermaid.css